# -*- coding: utf-8 -*-
XHS_PLATFORM_NAME = 'xhs'
DOUYIN_PLATFORM_NAME = 'dy'
KUAISHOU_PLATFORM_NAME = 'ks'
BILIBILI_PLATFORM_NAME = 'bili'

REQUEST_ID_HEADERS_KEY = "x-request-id"
RESPONSE_TYPE_JSON_HEADERS_KEY = "x-response-type"
RESPONSE_TYPE_JSON_HEADERS_VALUE = "json"